name: charm-helpers CI

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: 3.8
            env: pep8,py38
          - python-version: "3.10"
            env: pep8,py310
          - python-version: "3.12"
            env: pep8,py312

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install juju
      run: |
        sudo snap install juju --classic
    - name: Install packages
      run: |
        sudo apt -qq update
        sudo apt install --yes libapt-pkg-dev # For python-apt wheel build
        sudo apt install --yes bzr
        sudo apt install --yes rustc cargo
    - name: Install tox
      run: pip install tox
    - name: Test
      run: tox -c tox.ini -e ${{ matrix.env }}
